### ISSUE TITLE
Token Expiry is not set during creation

### ISSUE THREAD

**Issue by hansiemithun** [teifip/node-webtokens#1]
In this library, I see that token expiry is set after generation. Is it the expected behavior?

**Comment by teifip** [comment]
@hansiemithun - Thanks for your question. Not sure what you mean with "set after generation". 
If you intend to use the `exp` claim, you are supposed to include it in the payload before you invoke the `generate` method.  At verification time, if present in the payload, the `exp` claim is automatically processed. In summary:

`iat` claim:

- Automatically inserted in the payload at generation time;
- Processed at verification time only if you chain the `parse` method with the `setTokenLifetime` method.

`exp` claim:

- Up to the user to include it in the payload before generation;
- Automatically processed at verification time if present.

I hope this clarifies.

**Comment by hansiemithun** [comment]
Thanks for your response @teifip .

**Please clarify:**

> I could not see in an example from the documentation to set before creating token. Could you please provide here a small piece of program to set.
> 
> I was playing with this and I created a small program using this module here: https://github.com/hansiemithun/jwe-example
> 
> I am trying to understand even after the token is expired, I could still use the same token inside jwt.io to decode the payload. Is there a way to delete the token or make the existing token invalid for decode and see it externally? Or is it the expected behavior? Do we need to internally handle it in our application after expired?

**The doubt raised from this block of code:**

```
               parsedToken = jwt.parse(token)
                 .setTokenLifetime(120000)
                 .setAlgorithmList(['RS256', 'RS384'])
                 .setIssuer(['auth.mydomain.com'])
                 .setAudience(['A1B2C3D4E5.com.mydomain.myservice'])
                 .verify(key);
```
`setTokenLifetime` is set after `token` has been created

**Comment by teifip** [comment]
@hansiemithun - The `exp` claim goes in the payload. There is nothing magic about it. For example:
```
let payload = {
  iss: 'auth.mydomain.com',
  aud: 'A1B2C3D4E5.com.mydomain.myservice',
  sub: 'jack.sparrow@example.com',
  info: 'Hello World!',
  list: [1, 2, 3],
  exp: Math.floor(Date.now() / 1000) + 3600   // will expire in one hour, i.e. 3600s is the life cycle
};
```
The block of code with `setTokenLifetime` is related to `iat`, not to `exp`. Again:

`iat` is a fact of life. The `generate` method knows the exact moment when you're generating the token. On the other hand, the `iat` verification depends on how long you want to life cycle to be. You must puss this info at verification time with the `setTokelifetime` method.

The situation for `exp` is the reverse.  You must set it explicitly at generation time since it depends on how long you want the life cycle to be. On the other hand, at verification time it is a fact of life... if it is there, it immediately possible to know if the token has expired or not by comparing `exp` with the current time.

Nothing of this has anything to do with whether the token is usable or not! Signature (JWS) and decryption (JWE) have nothing to do with either the `iat` or `exp` claim (which are both part of the payload). It's your application policy to decide what you do with expired tokens.
